CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND lower(role) = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.owns_service_request(target_request_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE id = target_request_id AND client_id = auth.uid()
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.owns_service_request(uuid) TO authenticated;

CREATE TABLE IF NOT EXISTS public.camera_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE REFERENCES public.service_requests(id) ON DELETE CASCADE,
  stream_url text NOT NULL CHECK (stream_url ~ '^https://'),
  configured_by uuid NOT NULL REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.camera_access_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL REFERENCES public.service_requests(id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.camera_access_codes
  ADD COLUMN IF NOT EXISTS display_code text;

CREATE TABLE IF NOT EXISTS public.camera_access_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL REFERENCES public.service_requests(id) ON DELETE CASCADE,
  admin_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.camera_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_access_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_access_grants ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE ON TABLE public.camera_devices TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.camera_devices_id_seq TO authenticated;
GRANT SELECT ON TABLE public.camera_access_codes TO authenticated;

DROP POLICY IF EXISTS "Cliente recibe códigos de su cámara" ON public.camera_access_codes;
CREATE POLICY "Cliente recibe códigos de su cámara"
ON public.camera_access_codes FOR SELECT TO authenticated
USING (public.owns_service_request(request_id));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'camera_access_codes'
  ) THEN
    ALTER PUBLICATION supabase_realtime
      ADD TABLE public.camera_access_codes;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.request_camera_access(target_request_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  generated_code text;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.camera_devices WHERE request_id = target_request_id
  ) THEN
    RAISE EXCEPTION 'La cámara todavía no está configurada';
  END IF;

  generated_code := lpad(floor(random() * 1000000)::int::text, 6, '0');
  UPDATE public.camera_access_codes
    SET used_at = now(), display_code = NULL
    WHERE request_id = target_request_id AND used_at IS NULL;
  INSERT INTO public.camera_access_codes
    (request_id, code_hash, display_code, expires_at)
  VALUES (
    target_request_id,
    encode(digest(generated_code, 'sha256'), 'hex'),
    generated_code,
    now() + interval '5 minutes'
  );
  RETURN true;
END;
$$;

DROP POLICY IF EXISTS "Propietario o admin autorizado consulta cámara" ON public.camera_devices;
CREATE POLICY "Propietario o admin autorizado consulta cámara"
ON public.camera_devices FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = camera_devices.request_id
      AND service_requests.client_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.camera_access_grants
    WHERE camera_access_grants.request_id = camera_devices.request_id
      AND camera_access_grants.admin_id = auth.uid()
      AND camera_access_grants.expires_at > now()
  )
);

DROP POLICY IF EXISTS "Admin configura cámara" ON public.camera_devices;
CREATE POLICY "Admin configura cámara"
ON public.camera_devices FOR INSERT TO authenticated
WITH CHECK (public.is_admin() AND configured_by = auth.uid());

DROP POLICY IF EXISTS "Admin actualiza cámara" ON public.camera_devices;
CREATE POLICY "Admin actualiza cámara"
ON public.camera_devices FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin() AND configured_by = auth.uid());

CREATE OR REPLACE FUNCTION public.create_camera_access_code(target_request_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  generated_code text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE id = target_request_id AND client_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  generated_code := lpad(floor(random() * 1000000)::int::text, 6, '0');
  UPDATE public.camera_access_codes
    SET used_at = now()
    WHERE request_id = target_request_id AND used_at IS NULL;
  INSERT INTO public.camera_access_codes (request_id, code_hash, display_code, expires_at)
    VALUES (target_request_id, encode(digest(generated_code, 'sha256'), 'hex'), generated_code, now() + interval '5 minutes');
  RETURN generated_code;
END;
$$;

CREATE OR REPLACE FUNCTION public.redeem_camera_access_code(target_request_id uuid, plain_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  matched_id bigint;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  SELECT id INTO matched_id
  FROM public.camera_access_codes
  WHERE request_id = target_request_id
    AND code_hash = encode(digest(plain_code, 'sha256'), 'hex')
    AND used_at IS NULL
    AND expires_at > now()
  ORDER BY created_at DESC
  LIMIT 1;

  IF matched_id IS NULL THEN RETURN false; END IF;
  UPDATE public.camera_access_codes SET used_at = now(), display_code = NULL WHERE id = matched_id;
  DELETE FROM public.camera_access_grants
    WHERE request_id = target_request_id AND admin_id = auth.uid();
  INSERT INTO public.camera_access_grants (request_id, admin_id, expires_at)
    VALUES (target_request_id, auth.uid(), now() + interval '5 minutes');
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.create_camera_access_code(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.request_camera_access(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_camera_access_code(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_camera_access_code(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_camera_access(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_camera_access_code(uuid, text) TO authenticated;
