CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND lower(role) = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

CREATE TABLE IF NOT EXISTS public.installation_appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL UNIQUE REFERENCES public.service_requests(id) ON DELETE CASCADE,
  appointment_date date NOT NULL,
  appointment_time time NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.installation_appointments ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS unique_active_installation_slot
ON public.installation_appointments (appointment_date, appointment_time)
WHERE status <> 'cancelled';

CREATE OR REPLACE FUNCTION public.get_booked_installation_times(selected_date date)
RETURNS TABLE (appointment_time time)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT a.appointment_time
  FROM public.installation_appointments a
  WHERE a.appointment_date = selected_date
    AND a.status <> 'cancelled';
$$;

GRANT EXECUTE ON FUNCTION public.get_booked_installation_times(date) TO authenticated;

DROP POLICY IF EXISTS "Clientes consultan su cita" ON public.installation_appointments;
CREATE POLICY "Clientes consultan su cita"
ON public.installation_appointments FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = installation_appointments.request_id
      AND service_requests.client_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Clientes crean su cita" ON public.installation_appointments;
CREATE POLICY "Clientes crean su cita"
ON public.installation_appointments FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = installation_appointments.request_id
      AND service_requests.client_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Participantes actualizan citas" ON public.installation_appointments;
CREATE POLICY "Participantes actualizan citas"
ON public.installation_appointments FOR UPDATE TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = installation_appointments.request_id
      AND service_requests.client_id = auth.uid()
  )
)
WITH CHECK (
  public.is_admin()
  OR (
    status IN ('pending', 'cancelled')
    AND EXISTS (
      SELECT 1 FROM public.service_requests
      WHERE service_requests.id = installation_appointments.request_id
        AND service_requests.client_id = auth.uid()
    )
  )
);
