CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND lower(role) = 'admin'
  );
$$;

CREATE TABLE IF NOT EXISTS public.camera_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL UNIQUE REFERENCES public.service_requests(id) ON DELETE CASCADE,
  stream_url text NOT NULL CHECK (stream_url ~ '^https://'),
  configured_by uuid NOT NULL REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.camera_access_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL REFERENCES public.service_requests(id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.camera_access_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL REFERENCES public.service_requests(id) ON DELETE CASCADE,
  admin_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.camera_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_access_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.camera_access_grants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Propietario o admin autorizado consulta cámara" ON public.camera_devices;
CREATE POLICY "Propietario o admin autorizado consulta cámara"
ON public.camera_devices FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = camera_devices.request_id
      AND service_requests.client_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.camera_access_grants
    WHERE camera_access_grants.request_id = camera_devices.request_id
      AND camera_access_grants.admin_id = auth.uid()
      AND camera_access_grants.expires_at > now()
  )
);

DROP POLICY IF EXISTS "Admin configura cámara" ON public.camera_devices;
CREATE POLICY "Admin configura cámara"
ON public.camera_devices FOR INSERT TO authenticated
WITH CHECK (public.is_admin() AND configured_by = auth.uid());

DROP POLICY IF EXISTS "Admin actualiza cámara" ON public.camera_devices;
CREATE POLICY "Admin actualiza cámara"
ON public.camera_devices FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin() AND configured_by = auth.uid());

CREATE OR REPLACE FUNCTION public.create_camera_access_code(target_request_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  generated_code text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE id = target_request_id AND client_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  generated_code := lpad(floor(random() * 1000000)::int::text, 6, '0');
  UPDATE public.camera_access_codes
    SET used_at = now()
    WHERE request_id = target_request_id AND used_at IS NULL;
  INSERT INTO public.camera_access_codes (request_id, code_hash, expires_at)
    VALUES (target_request_id, encode(digest(generated_code, 'sha256'), 'hex'), now() + interval '10 minutes');
  RETURN generated_code;
END;
$$;

CREATE OR REPLACE FUNCTION public.redeem_camera_access_code(target_request_id bigint, plain_code text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  matched_id bigint;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  SELECT id INTO matched_id
  FROM public.camera_access_codes
  WHERE request_id = target_request_id
    AND code_hash = encode(digest(plain_code, 'sha256'), 'hex')
    AND used_at IS NULL
    AND expires_at > now()
  ORDER BY created_at DESC
  LIMIT 1;

  IF matched_id IS NULL THEN RETURN false; END IF;
  UPDATE public.camera_access_codes SET used_at = now() WHERE id = matched_id;
  DELETE FROM public.camera_access_grants
    WHERE request_id = target_request_id AND admin_id = auth.uid();
  INSERT INTO public.camera_access_grants (request_id, admin_id, expires_at)
    VALUES (target_request_id, auth.uid(), now() + interval '30 minutes');
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.create_camera_access_code(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_camera_access_code(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_camera_access_code(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_camera_access_code(bigint, text) TO authenticated;
