CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND lower(role) = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

CREATE TABLE IF NOT EXISTS public.service_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL REFERENCES public.service_requests(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sender_role text NOT NULL CHECK (sender_role IN ('client', 'admin')),
  message text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 1000),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.service_messages ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS service_messages_request_created_idx
  ON public.service_messages (request_id, created_at);

DROP POLICY IF EXISTS "Participantes pueden leer mensajes" ON public.service_messages;
CREATE POLICY "Participantes pueden leer mensajes"
ON public.service_messages FOR SELECT TO authenticated
USING (
  public.is_admin()
  OR EXISTS (
    SELECT 1 FROM public.service_requests
    WHERE service_requests.id = service_messages.request_id
      AND service_requests.client_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Participantes pueden enviar mensajes" ON public.service_messages;
CREATE POLICY "Participantes pueden enviar mensajes"
ON public.service_messages FOR INSERT TO authenticated
WITH CHECK (
  sender_id = auth.uid()
  AND (
    (public.is_admin() AND sender_role = 'admin')
    OR (
      sender_role = 'client'
      AND EXISTS (
        SELECT 1 FROM public.service_requests
        WHERE service_requests.id = service_messages.request_id
          AND service_requests.client_id = auth.uid()
      )
    )
  )
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'service_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.service_messages;
  END IF;
END $$;
